minmunlee/2025-algorithm-study

01월/1주차/[BOJ] 사이클 단어/Mun.java
01월/1주차/[BOJ] 아즈버의 이빨 자국/Mun.java
01월/1주차/[PRGRMS] 베스트앨범/Mun.java

- [사이클단어]()
- [아즈버의 이빨 자국]()
- [베스트앨범]()
<br>
- [FrontEnd 개발자 찾기](https://school.programmers.co.kr/learn/courses/30/lessons/276035)
- [언어별 개발자 분류하기](https://school.programmers.co.kr/learn/courses/30/lessons/276036)
- [프로그래머스 특정 기간동안 대여 가능한 자동차들의 대여비용 구하기](https://school.programmers.co.kr/learn/courses/30/lessons/157339)
- sql 비트 연산 개념의 부족
- 스터디에서의 풀이를 듣고 이해한 후 재도전할 계획입니다.
<br>
- Map 출력시 forEach 를 사용할 수 있다는 것을 알게 되었습니다.
<br>
- sql에서의 비트 연산에 대해 공부해야 겠다는 생각이 들었습니다.
- sql에 대해서, 풀었던 문제를 다시 살펴보는 시간을 가져야겠다고 생각했습니다.

Mun: 1월 1주차 문제풀이

---

01월/2주차/[BOJ] 강의실/Mun.java
01월/2주차/[BOJ] 크리스마스 선물/Mun.java
01월/2주차/[PRGRMS] 디스크 컨트롤러/Mun.java

- [강의실](https://www.acmicpc.net/problem/1374)
- [크리스마스 선물](https://www.acmicpc.net/problem/14235)
- [디스크 컨트롤러](https://school.programmers.co.kr/learn/courses/30/lessons/42627)
<br>
- [상품을 구매한 회원 비율 구하기](https://school.programmers.co.kr/learn/courses/30/lessons/131534)
- [멸종위기의 대장균 찾기](https://school.programmers.co.kr/learn/courses/30/lessons/301651)
- Sql 문법에 대한 이해도가 부족하다고 느낌
- Sql 의 재귀 함수에 대해 이해하고 문제 풀이에 재도전 할 것이다.
<br>
- 우선순위 큐에 대해 커스텀 정렬 방식을 처음 적용해보았다
<br>

Mun: 1월 2주차 문제풀이

---

01월/2주차/[BOJ] 강의실/Lee.java
01월/2주차/[BOJ] 크리스마스 선물/Lee.java
01월/2주차/[PRGRMS] 디스크 컨트롤러/Lee.java
01월/2주차/[SQL] 상품을 구매한 회원 비율 구하기/Lee.sql

- [강의실](https://www.acmicpc.net/problem/1374)
- [크리스마스 선물](https://www.acmicpc.net/problem/14235)
- [디스크 컨트롤러](https://school.programmers.co.kr/learn/courses/30/lessons/42627)
- [상품을 구매한 회원 비율 구하기](https://school.programmers.co.kr/learn/courses/30/lessons/131534)
<br>
- [멸종위기의 대장균 찾기](https://school.programmers.co.kr/learn/courses/30/lessons/301651)
- SQL 문법에 대해 깊게 알지 못해서 문제 접근 방식에 대해 감을 잡지 못한 것 같음.
- SQL 문법에 대한 깊은 공부가 필요
<br>
<br>

Lee: 1월 2주차 문제풀이

---

01월/3주차/[BOJ] 온라인 판매/Min.java
01월/3주차/[BOJ] 절댓값 힙/Min.java
01월/3주차/[BOJ] 행복 유치원/Min.java

- [온라인 판매](https://www.acmicpc.net/problem/1246)
- [절댓값 힙](https://www.acmicpc.net/problem/11286)
- [행복 유치원](https://www.acmicpc.net/problem/13164)
<br>
- [조이스틱](https://school.programmers.co.kr/learn/courses/30/lessons/42860)
- 제가 구현한 것보다 더 많은 조건들을 생각해 보아야 하는데 그 조건에 따라 어떻게 구현을 해야할지 생각이 나지 않았습니다 😭
- 다른 정답 코드들을 보며 이해해볼 계획입니다.
<br>
- 우선순위 큐의 정렬을 사용자화 하는 법을 좀 더 공부할 수 있었습니다. 
<br>
- 그리디에 대해 좀 더 공부할 필요성을 느꼈습니다..

Min: 1월 3주차 문제 풀이

---

01월/3주차/[BOJ] 온라인 판매/Lee.java
01월/3주차/[BOJ] 절댓값 힙/Lee.java
01월/3주차/[BOJ] 행복 유치원/Lee.java

- [온라인 판매](https://www.acmicpc.net/problem/1246)
- [절댓값 힙](https://www.acmicpc.net/problem/11286)
- [행복 유치원](https://www.acmicpc.net/problem/13164)
<br>
- [조이스틱](https://school.programmers.co.kr/learn/courses/30/lessons/42860)
- 다음 위치로 갈 방향을 정하는데에 탐욕법을 적용시킬 아이디어가 떠오르질 않음
- 더 다양한 유형의 그리디 문제를 풀어보면서 노하우를 익혀야 할듯함.
<br>
<br>

Lee: 1월 3주차 문제풀이

---

01월/3주차/[BOJ] 온라인 판매/Mun.java
01월/4주차/[BOJ] 그림/Mun.java
01월/4주차/[BOJ] 상범 빌딩/Main.java
01월/4주차/[BOJ] 상범 빌딩/Mun.java
01월/4주차/[BOJ] 수리공 항승/Mun.java
01월/4주차/[PRGRMS] 네트워크/Mun.java

- [그림](https://www.acmicpc.net/problem/1926)
- [상범 빌딩](https://www.acmicpc.net/problem/6593)
- [수리공 항승](https://www.acmicpc.net/problem/1449)
- [온라인 판매](https://www.acmicpc.net/problem/1246)
- [네트워크](https://school.programmers.co.kr/learn/courses/30/lessons/43162)
<br>
<br>
<br>

Mun: 1월 4주차 문제풀이

---

01월/4주차/[BOJ] 그림/Lee.java
01월/4주차/[BOJ] 상범 빌딩/Lee.java
01월/4주차/[BOJ] 수리공 항승/Lee.java
01월/4주차/[PRGRMS] 네트워크/Lee.java

- [그림](https://www.acmicpc.net/problem/1926)
- [상범 빌딩](https://www.acmicpc.net/problem/6593)
- [수리공 항승](https://www.acmicpc.net/problem/1449)
- [네트워크](https://school.programmers.co.kr/learn/courses/30/lessons/43162)
<br>
X
<br>
<br>

Lee: 1월 4주차 문제풀이

---

01월/4주차/[BOJ] 그림/Min.java
01월/4주차/[BOJ] 수리공 항승/Min.java
01월/4주차/[PRGRMS] 네트워크/Min.java

- [그림](https://www.acmicpc.net/problem/1926)
- [수리공 항승](https://www.acmicpc.net/problem/1449)
- [네트워크](https://school.programmers.co.kr/learn/courses/30/lessons/43162)
<br>
- [상범 빌딩](https://www.acmicpc.net/problem/6593)
어떻게 풀어야할지 감이 안와서 풀이법을 보아도 삼중 배열을 이용한 그래프 탐색 문제는 아직 이해하는데 시간이 걸리는 듯합니다..
- 유사 문제중 조금 더 난이도가 낮은 문제부터 다시 풀어 본 뒤 감을 익혀 다시 풀어보도록 해보겠습니다.
<br>
<br>

Min: 1월 4주차 문제 풀이

---

01월/3주차/[BOJ] 온라인 판매/Mun.java
01월/4주차/[BOJ] 그림/Lee.java
01월/4주차/[BOJ] 그림/Min.java
01월/4주차/[BOJ] 그림/Mun.java
01월/4주차/[BOJ] 상범 빌딩/Lee.java
01월/4주차/[BOJ] 상범 빌딩/Mun.java
01월/4주차/[BOJ] 수리공 항승/Lee.java
01월/4주차/[BOJ] 수리공 항승/Min.java
01월/4주차/[BOJ] 수리공 항승/Mun.java
01월/4주차/[PRGRMS] 네트워크/Lee.java
01월/4주차/[PRGRMS] 네트워크/Min.java
01월/4주차/[PRGRMS] 네트워크/Mun.java

- [그림](https://www.acmicpc.net/problem/1926)
- [상범 빌딩](https://www.acmicpc.net/problem/6593)
- [수리공 항승](https://www.acmicpc.net/problem/1449)
- [네트워크](https://school.programmers.co.kr/learn/courses/30/lessons/43162)
시원
- [온라인 판매](https://www.acmicpc.net/problem/1246)

[SOLVE] 민문리 1월 4주차 문제 풀이

---

02월/1주차/[BOJ] LCS/Min.java
02월/1주차/[BOJ] 점프 점프/Min.java
02월/1주차/[BOJ] 정수 삼각형/Min.java

- [LCS](https://www.acmicpc.net/problem/9251)
- [점프점프](https://www.acmicpc.net/problem/14248)
- [정수 삼각형](https://www.acmicpc.net/problem/1932)
<br>
- [N으로 표현](https://school.programmers.co.kr/learn/courses/30/lessons/42895)
- 어떻게 문제에 접근해야하는지 감이 오지 않습니다.
- 스터디 이후 다른 해설을 보며 감을 익혀보겠습니다.
<br>
- 동적 계획법 문제를 풀면서 하나부터 차례로 결과를 도출해보며 나오는 규칙을 파악해 점화식을 만들어 보는 연습을 해보며 감을 조금 익혀보았습니다.
<br>

Min: 2월 1주차 문제 풀이

---

02월/1주차/[BOJ] LCS/Lee.java
02월/1주차/[BOJ] 점프 점프/Lee.java
02월/1주차/[BOJ] 정수 삼각형/Lee.java

- [LCS](https://www.acmicpc.net/problem/9251)
- [정수 삼각형](https://www.acmicpc.net/problem/1932)
- [점프 점프](https://www.acmicpc.net/problem/14248)
<br>
- [N으로 표현](https://school.programmers.co.kr/learn/courses/30/lessons/42895)
<br>
LCS문제 유형과 해결 방법에 대해 공부할 수 있었습니다.
[참고한 블로그](https://velog.io/@emplam27/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-%EA%B7%B8%EB%A6%BC%EC%9C%BC%EB%A1%9C-%EC%95%8C%EC%95%84%EB%B3%B4%EB%8A%94-LCS-%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-Longest-Common-Substring%EC%99%80-Longest-Common-Subsequence)
<br>

Lee: 2월 1주차 문제풀이

---

02월/2주차/[BOJ] N번째 큰 수/Mun.java
02월/2주차/[BOJ] 과제/Mun.java
02월/2주차/[BOJ] 오르막 수/Mun.java
02월/2주차/[PRGRMS] 이중우선순위큐/Mun.java

- [과제](https://www.acmicpc.net/problem/13904)
- [N번째 큰수](https://www.acmicpc.net/problem/2075)
- [오르막 수](https://www.acmicpc.net/problem/11057)
- [이중우선순위큐](https://school.programmers.co.kr/learn/courses/30/lessons/42628)
<br>
🙅‍♀️
<br>
10,007로 나누는 연산에 대해 궁금증을 느껴서 찾아보다가 모듈러 연산이라는 개념을 알게되었습니다.
<br>

Mun: 2월 2주차 문제 풀이

---

02월/2주차/[BOJ] N번째 큰 수/Min.java
02월/2주차/[BOJ] 과제/Min.java
02월/2주차/[PRGRMS] 이중우선순위큐/Min.java

- [N번째 큰 수](https://www.acmicpc.net/problem/2075)
- [과제](https://www.acmicpc.net/problem/13904)
- [이중우선순위큐](https://school.programmers.co.kr/learn/courses/30/lessons/42628)
- [오르막수](https://www.acmicpc.net/problem/11057)
<br>
- 점화식을 찾는 과정이 어려웠습니다.
- 좀 더 DP 문제를 많이 풀어보아야할거같습니다.
<br>
<br>

Min: 2월 2주차 문제풀이

---

02월/2주차/[BOJ] N번째 큰 수/Lee.java
02월/2주차/[BOJ] 과제/Lee.java
02월/2주차/[BOJ] 오르막 수/Lee.java
02월/2주차/[PRGRMS] 이중우선순위큐/Lee.java

- [과제](https://www.acmicpc.net/problem/13904)
- [N번째 큰수](https://www.acmicpc.net/problem/2075)
- [오르막 수](https://www.acmicpc.net/problem/11057)
- [이중우선순위큐](https://school.programmers.co.kr/learn/courses/30/lessons/42628)
<br>
X
<br>
백준 DP 문제인 오르막 수의 해결방법을 찾지 못해 답은 보지 않고 다른 사람의 풀이 방법을 따라해보았습니다. (표 그리기)
<br>

Lee: 2월 2주차 문제풀이

---

02월/2주차/[BOJ] N번째 큰 수/Lee.java
02월/2주차/[BOJ] N번째 큰 수/Min.java
02월/2주차/[BOJ] N번째 큰 수/Mun.java
02월/2주차/[BOJ] 과제/Lee.java
02월/2주차/[BOJ] 과제/Min.java
02월/2주차/[BOJ] 과제/Mun.java
02월/2주차/[BOJ] 오르막 수/Lee.java
02월/2주차/[BOJ] 오르막 수/Mun.java
02월/2주차/[PRGRMS] 이중우선순위큐/Lee.java
02월/2주차/[PRGRMS] 이중우선순위큐/Min.java
02월/2주차/[PRGRMS] 이중우선순위큐/Mun.java

- [과제](https://www.acmicpc.net/problem/13904)
- [N번째 큰수](https://www.acmicpc.net/problem/2075)
- [오르막 수](https://www.acmicpc.net/problem/11057)
- [이중우선순위큐](https://school.programmers.co.kr/learn/courses/30/lessons/42628)
<br>

[SOLVE] 민문리 2월 2주차 문제 풀이

---

02월/3주차/[BOJ] 사과 담기 게임/Min.java
02월/3주차/[BOJ] 센티와 마법의 뿅망치/Min.java
02월/3주차/[BOJ] 수 묶기/Min.java

- [사과 담기 게임](https://www.acmicpc.net/problem/2828)
- [센티와 마법의 뿅망치](https://www.acmicpc.net/problem/19638)
- [수 묶기](https://www.acmicpc.net/problem/1744)
<br>
- [섬 연결하기](https://school.programmers.co.kr/learn/courses/30/lessons/42861)
- 접근 방법에 대해 아직 모르겠습니다.
<br>
<br>

Min: 2월 3주차 문제 풀이

---

02월/3주차/[BOJ] 사과 담기 게임/Mun.java
02월/3주차/[BOJ] 센티와 마법의 뿅망치/Mun.java
02월/3주차/[BOJ] 수 묶기/Mun.java
02월/3주차/[PRGRMS] 섬 연결하기/Mun.java

- [센티와 마법의 뿅망치](https://www.acmicpc.net/problem/19638)
- [사과 담기 게임](https://www.acmicpc.net/problem/2828)
- [수 묶기](https://www.acmicpc.net/problem/1744)
- [섬 연결하기](https://school.programmers.co.kr/learn/courses/30/lessons/42861)
<br>
🙅‍♀️
<br>
<br>

Mun: 2월 3주차 문제 풀이 

---

02월/3주차/[BOJ] 사과 담기 게임/Lee.java
02월/3주차/[BOJ] 사과 담기 게임/Min.java
02월/3주차/[BOJ] 사과 담기 게임/Mun.java
02월/3주차/[BOJ] 센티와 마법의 뿅망치/Lee.java
02월/3주차/[BOJ] 센티와 마법의 뿅망치/Min.java
02월/3주차/[BOJ] 센티와 마법의 뿅망치/Mun.java
02월/3주차/[BOJ] 수 묶기/Lee.java
02월/3주차/[BOJ] 수 묶기/Min.java
02월/3주차/[BOJ] 수 묶기/Mun.java
02월/3주차/[PRGRMS] 섬 연결하기/Lee.java
02월/3주차/[PRGRMS] 섬 연결하기/Mun.java

- [센티와 마법의 뿅망치](https://www.acmicpc.net/problem/19638)
- [사과 담기 게임](https://www.acmicpc.net/problem/2828)
- [수 묶기](https://www.acmicpc.net/problem/1744)
- [섬 연결하기](https://school.programmers.co.kr/learn/courses/30/lessons/42861)
<br>

[SOLVE] 민문리 2월 3주차 문제 풀이

---

03월/1주차/[BOJ] 상자넣기/Mun.java
03월/1주차/[BOJ] 잃어버린 괄호/Mun.java
03월/1주차/[PRGRMS] 정수 삼각형/Mun.java

- [상자 넣기](https://www.acmicpc.net/problem/1965)
- [잃어버린 괄호](https://www.acmicpc.net/problem/1541)
- [정수 삼각형](https://school.programmers.co.kr/learn/courses/30/lessons/43105)
<br>
- [동전 1](https://www.acmicpc.net/problem/2293)
- 규칙을 찾지 못해 점화식을 세울 수 없었습니다.
- 풀이를 이해한 후, 다시 점화식을 세워보며 문제를 풀 계획입니다.
<br>
<br>

Mun: 3월 1주차 문제 풀이

---

03월/1주차/[BOJ] 동전 1/Min.java
03월/1주차/[BOJ] 잃어버린 괄호/Min.java
03월/1주차/[PRGRMS] 정수 삼각형/Min.java

- [동전 1](https://www.acmicpc.net/problem/2293)
- [잃어버린 괄호](https://www.acmicpc.net/problem/1541)
- [정수 삼각형](https://school.programmers.co.kr/learn/courses/30/lessons/43105)
<br>
- [상자 넣기](https://www.acmicpc.net/problem/1965)
- 열심히 점화식 찾는 연습을 하겠습니다...
<br>
- 백준_동전 1을 풀면서 작성한 점화식
- 백준_잃어버린 괄호를 풀면서 작성한 풀이
<br>
- dp를 마스터하는 그 날까지 화이팅!!!!

Min: 3월 1주차 문제 풀이

---

03월/1주차/[BOJ] 동전 1/Min.java
03월/1주차/[BOJ] 상자넣기/Mun.java
03월/1주차/[BOJ] 잃어버린 괄호/Min.java
03월/1주차/[BOJ] 잃어버린 괄호/Mun.java
03월/1주차/[PRGRMS] 정수 삼각형/Min.java
03월/1주차/[PRGRMS] 정수 삼각형/Mun.java

- [동전 1](https://www.acmicpc.net/problem/2293)
- [상자 넣기](https://www.acmicpc.net/problem/1965)
- [잃어버린 괄호](https://www.acmicpc.net/problem/1541)
- [정수 삼각형](https://school.programmers.co.kr/learn/courses/30/lessons/43105)
<br>

[SOLVE] 민문리 3월 1주차 문제 풀이

---

01월/3주차/[PRGRMS] 조이스틱/Mun.java
03월/3주차/[BOJ] 거짓말/Mun.java
03월/3주차/[BOJ] 마니또/Mun.java
03월/3주차/[BOJ] 숫자판 점프/Mun.java
03월/3주차/[PRGRMS] 가장 먼 노드/Mun.java

- [거짓말](https://www.acmicpc.net/problem/1043)
- [숫자판 점프](https://www.acmicpc.net/problem/2210)
- [마니또](https://www.acmicpc.net/problem/5107)
- [가장 먼 노드](https://school.programmers.co.kr/learn/courses/30/lessons/49189)
- 1월 3주차 문제 [조이스틱](https://school.programmers.co.kr/learn/courses/30/lessons/42860)
<br>
🙅‍♀️
<br>
그래프 문제 풀이에 대한 이해력이 조금 오른 것 같습니다.
<br>
더 간단한 풀이 방법이 있는지 연구 필요

Mun: 3월 3주차 문제 풀이

---

03월/3주차/[BOJ] 거짓말/Min.java
03월/3주차/[BOJ] 숫자판 점프/Min.java
03월/3주차/[PRGRMS] 가장 먼 노드/Min.java

- [거짓말](https://www.acmicpc.net/problem/1043)
- [숫자판 점프](https://www.acmicpc.net/problem/2210)
- [가장 먼 노드](https://school.programmers.co.kr/learn/courses/30/lessons/49189)
<br>
- [마니또](https://www.acmicpc.net/problem/5107)
문제 자체를 이해하지 못했습니다.
설명을 들어보며 문제를 이해해보겠습니다..!
<br>
- 인접 리스트로 그래프 문제 푸는 법을 공부하게 되었습니다
<br>

Min: 3월 3주차 문제 풀이

---

01월/3주차/[PRGRMS] 조이스틱/Mun.java
03월/3주차/[BOJ] 거짓말/Min.java
03월/3주차/[BOJ] 거짓말/Mun.java
03월/3주차/[BOJ] 마니또/Mun.java
03월/3주차/[BOJ] 숫자판 점프/Min.java
03월/3주차/[BOJ] 숫자판 점프/Mun.java
03월/3주차/[PRGRMS] 가장 먼 노드/Min.java
03월/3주차/[PRGRMS] 가장 먼 노드/Mun.java

- [거짓말](https://www.acmicpc.net/problem/1043)
- [숫자판 점프](https://www.acmicpc.net/problem/2210)
- [마니또](https://www.acmicpc.net/problem/5107)
- [가장 먼 노드](https://school.programmers.co.kr/learn/courses/30/lessons/49189)
mun
-  [조이스틱](https://school.programmers.co.kr/learn/courses/30/lessons/42860) (1월 3주차)

[SOLVE] 민문리 3월 3주차 문제 풀이

---

03월/4주차/[BOJ] 아기 상어 2/Min.java
03월/4주차/[BOJ] 한 줄로 서기/Min.java
03월/4주차/[PRGRMS] 단속카매라/Min.java

- [아기 상어2](https://www.acmicpc.net/problem/17086)
- [한 줄로 서기](https://www.acmicpc.net/problem/1138)
- [단속 카메라](https://school.programmers.co.kr/learn/courses/30/lessons/42884)
<br>
- [단어 수학](https://www.acmicpc.net/problem/1339)
- 좀 더 해결 방법을 고민해봐야 할 것 같습니다.
<br>
- bfs를 풀때 노드와 노드 사이의 거리를 구할 때
-   distance와 같은 배열 하나를 지정해서 거리가 멀어질 수록 이전 노드 값에서 1을 더해주는 방법을 활용하면 된 다는 것을 다시 공부하게 되었습니다.
<br>

Min: 3월 4주차 문제 풀이

---

03월/4주차/[BOJ] 단어 수학/Mun.java
03월/4주차/[BOJ] 아기 상어 2/Min.java
03월/4주차/[BOJ] 아기 상어 2/Mun.java
03월/4주차/[BOJ] 한 줄로 서기/Min.java
03월/4주차/[BOJ] 한 줄로 서기/Mun.java
03월/4주차/[PRGRMS] 단속카매라/Min.java
03월/4주차/[PRGRMS] 단속카매라/Mun.java

- [단어수학](https://www.acmicpc.net/problem/1339)
- [아기 상어 2](https://www.acmicpc.net/problem/17086)
- [한 줄로 서기](https://www.acmicpc.net/problem/1138)
- [단속카메라](https://school.programmers.co.kr/learn/courses/30/lessons/42884)
<br>

[SOLVE] 민문리 3월 4주차 문제 풀이 

---

03월/5주차/[BOJ] 도시와 비트코인/Mun.java
03월/5주차/[BOJ] 물통/Mun.java
03월/5주차/[BOJ] 주식/Mun.java

- [물통](https://www.acmicpc.net/problem/2251)
- [도시와 비트코인](https://www.acmicpc.net/problem/31575)
- [주식](https://www.acmicpc.net/problem/11501)
<br>
- [아이템 줍기](https://school.programmers.co.kr/learn/courses/30/lessons/87694)
구현 방법에 대해 생각하는 데에 긴 시간을 들이지 못했습니다.
좀 더 시간을 들여 구현해 볼 계획입니다.
<br>
앞으로 그리디 문제를 풀 때 거꾸로 생각해볼 것 같습니다.
<br>

Mun: 3월 5주차 문제 풀이

---

03월/5주차/[BOJ] 도시와 비트코인/Min.java
03월/5주차/[BOJ] 물통/Min.java
03월/5주차/[BOJ] 주식/Min.java

- [도시와 비트 코인](https://www.acmicpc.net/problem/31575)
- [물통](https://www.acmicpc.net/problem/2251)
- [주식](https://www.acmicpc.net/problem/11501)
- []()
<br>
- [아이템 줍기](https://school.programmers.co.kr/learn/courses/30/lessons/87694)
- 여러 사각형을 겹쳤을 때 테두리를 구하는 방법을 찾지 못했습니다.
<br>
<br>

Min: 3월 5주차 문제 풀이

---

03월/5주차/[BOJ] 도시와 비트코인/Min.java
03월/5주차/[BOJ] 도시와 비트코인/Mun.java
03월/5주차/[BOJ] 물통/Min.java
03월/5주차/[BOJ] 물통/Mun.java
03월/5주차/[BOJ] 주식/Min.java
03월/5주차/[BOJ] 주식/Mun.java

- [도시와 비트 코인](https://www.acmicpc.net/problem/31575)
- [물통](https://www.acmicpc.net/problem/2251)
- [주식](https://www.acmicpc.net/problem/11501)
- [아이템 줍기](https://school.programmers.co.kr/learn/courses/30/lessons/87694)
- [아이템 줍기](https://school.programmers.co.kr/learn/courses/30/lessons/87694)
<br>

[SOLVE] 민문리 3월 5주차 문제 풀이

---

04월/1주차/[BOJ] 거울/Mun.java
04월/1주차/[BOJ] 너구리 구구/Mun.java
04월/1주차/[BOJ] 사탕 게임/Mun.java

- [거울](https://www.acmicpc.net/problem/2344)
- [사탕 게임](https://www.acmicpc.net/problem/2344)
- [너구리 구구](https://www.acmicpc.net/problem/18126)
풀이과정
<br>
- [서버 증설 횟수](https://school.programmers.co.kr/learn/courses/30/lessons/389479#qna)
문제를 제대로 파악하지 못했습니다.
시간을 내서 문제를 다시 읽어보고 해결하겠습니다.
<br>
<br>
코드를 더 간단하게 작성할 수 있는 방법이 있는지 알아볼 계획입니다.

Mun: 4월 1주차 문제 풀이

---

04월/1주차/[BOJ] 거울/Min.java
04월/1주차/[BOJ] 사탕 게임/Min.java
04월/1주차/[PRGRMS] 서버 증설 횟수/Min.java

- [거울](https://www.acmicpc.net/problem/2344)
- [사탕 게임](https://www.acmicpc.net/problem/2344)
- [서버 증설 횟수](https://school.programmers.co.kr/learn/courses/30/lessons/389479#qna)
<br>
- [너구리 구구](https://www.acmicpc.net/problem/18126)
- 접근법이 다익스트라 인거같은데 풀 시간이 더 필요한 것 같습니다.
- 가중치가 있는 그래프에 대해 좀 더 공부해보고 풀어보겠습니다.
<br>
- 구현 문제는 문제를 풀고나서 추후 복습하는 시간이 필요하다는 생각이 들었습니다. 다시 풀이를 보니 까먹네요..
- [거울 문제 풀이 과정]
<br>

Min: 4월 1주차 문제 풀이

---

04월/1주차/[BOJ] 거울/Min.java
04월/1주차/[BOJ] 거울/Mun.java
04월/1주차/[BOJ] 너구리 구구/Mun.java
04월/1주차/[BOJ] 사탕 게임/Min.java
04월/1주차/[BOJ] 사탕 게임/Mun.java
04월/1주차/[PRGRMS] 서버 증설 횟수/Min.java

- [거울](https://www.acmicpc.net/problem/2344)
- [사탕 게임](https://www.acmicpc.net/problem/2344)
- [너구리 구구](https://www.acmicpc.net/problem/18126)
- [서버 증설 횟수](https://school.programmers.co.kr/learn/courses/30/lessons/389479#qna)

[SOLVE] 민문리 4월 1주차 문제 풀이

---

04월/2주차/[BOJ] 달팽이/Mun.java
04월/2주차/[BOJ] 중간고사 채점/Mun.java
04월/2주차/[PRGRMS] 숫자 카드 나누기/Mun.java

- [달팽이](https://www.acmicpc.net/problem/1913)
- [중간고사 채점](https://www.acmicpc.net/problem/15702)
- [숫자 카드 나누기](https://school.programmers.co.kr/learn/courses/30/lessons/135807)
<br>
- [스도쿠](https://www.acmicpc.net/problem/2239)
정확한 구현 방법을 찾지 못했습니다.
조금 더 고민해 보거나, 다른 사람의 풀이를 참고해 다시 도전해 볼 계획입니다.
<br>
<br>

Mun: 4월 2주차 문제 풀이

---

04월/2주차/[BOJ] 달팽이/Min.java
04월/2주차/[BOJ] 중간고사 채점/Min.java
04월/2주차/[PRGRMS] 숫자 카드 나누기/Min.java

- [달팽이](https://www.acmicpc.net/problem/1913)
- [중간고사 채점](https://www.acmicpc.net/problem/15702)
- [숫자 카드 나누기](https://school.programmers.co.kr/learn/courses/30/lessons/135807)
<br>
- [스도쿠](https://www.acmicpc.net/problem/2239)
- 3*3 구간안에서 숫자 판별법을 아직 찾지 못했습니다.
- 풀이법을 보고 참고해서 풀어보겠습니다.
<br>
<br>

Min: 4월 2주차 문제 풀이

---

04월/1주차/[BOJ] 너구리 구구/Min.java
04월/3주차/[BOJ] 빗물/Min.java
04월/3주차/[BOJ] 빙고/Min.java
04월/3주차/[PRGRMS] 미로 탈출/Min.java

- [빗물](https://www.acmicpc.net/problem/14719)
- [빙고](https://www.acmicpc.net/problem/2578)
- [너구리 구구](https://www.acmicpc.net/problem/18126) (4월 1주차 문제 Resolve)
- [미로 탈출](https://school.programmers.co.kr/learn/courses/30/lessons/159993)
<br>
- [병든 나이트](https://school.programmers.co.kr/learn/courses/30/lessons/159993)
- 이동 횟수에 대한 제약 조건 이해를 제대로 하지 못했습니다.
- 다른 풀이를 참고하거나 유사 알고리즘 문제를 공부해볼 계획입니다.
<br>
<br>

Min: 4월 3주차 문제 풀이

---

03월/5주차/[PRGRMS] 아이템 줍기/Mun.java
04월/1주차/[PRGRMS] 서버 증설 횟수/Mun.java
04월/3주차/[BOJ] 빗물/Mun.java
04월/3주차/[BOJ] 빙고/Mun.java
04월/3주차/[PRGRMS] 미로 탈출/Mun.java

- [빗물](https://www.acmicpc.net/problem/14719)
- [빙고](https://www.acmicpc.net/problem/2578)
- [미로 탈출](https://school.programmers.co.kr/learn/courses/30/lessons/159993)
- [아이템 줍기](https://school.programmers.co.kr/learn/courses/30/lessons/87694) (3월 5주차 문제)
- [서버 증설 횟수](https://school.programmers.co.kr/learn/courses/30/lessons/389479) (4월 1주차 문제)
- ![4_3풀이](https://github.com/user-attachments/assets/8937422c-da7b-47c9-8533-94a855fcf0c7)
<br>
- [병든 나이트](https://www.acmicpc.net/problem/1783)
최대한 많은 칸을 방문하도록 구현하는 방법이 떠오르지 않았습니다.
풀이를 듣고 다시 도전할 계획입니다.
<br>
<br>
그리디 알고리즘 문제의 풀이 방법을 잘 떠올릴 수 있도록 보완해야 할 것 같습니다.

Mun: 4월 3주차 문제 풀이

---

03월/5주차/[PRGRMS] 아이템 줍기/Mun.java
04월/1주차/[BOJ] 너구리 구구/Min.java
04월/1주차/[PRGRMS] 서버 증설 횟수/Mun.java
04월/3주차/[BOJ] 빗물/Min.java
04월/3주차/[BOJ] 빗물/Mun.java
04월/3주차/[BOJ] 빙고/Min.java
04월/3주차/[BOJ] 빙고/Mun.java
04월/3주차/[PRGRMS] 미로 탈출/Min.java
04월/3주차/[PRGRMS] 미로 탈출/Mun.java

- [빗물](https://www.acmicpc.net/problem/14719)
- [빙고](https://www.acmicpc.net/problem/2578)
- [미로 탈출](https://school.programmers.co.kr/learn/courses/30/lessons/159993)
- [병든 나이트](https://school.programmers.co.kr/learn/courses/30/lessons/159993)
- [아이템 줍기](https://school.programmers.co.kr/learn/courses/30/lessons/87694) (3월 5주차 문제)
- [너구리 구구](https://www.acmicpc.net/problem/18126) (4월 1주차 문제)
- [서버 증설 횟수](https://school.programmers.co.kr/learn/courses/30/lessons/389479) (4월 1주차 문제)
<br>

[SOLVE] 민문리 4월 3주차 문제 풀이

---

05월/1주차/[BOJ] The Game of Death/Min.java
05월/1주차/[BOJ] 과제는 끝나지 않아!/Min.java
05월/1주차/[PRGRMS] [3차] 방금그곡/Min.java

- [The Game of Death](https://www.acmicpc.net/problem/11558)
- [과제는 끝나지 않아!](https://www.acmicpc.net/problem/11558)
- [방금그곡](https://www.acmicpc.net/problem/11558)
<br>
- [4와 7](https://www.acmicpc.net/problem/2877)
- 접근한 방식이 틀렸다고 나오는데 접근 방식 외의 방법이 떠오르지 않아 해결하지 못했습니다.
- 다른 풀이 방법을 참고해보겠습니다.
<br>
- Date 포멧팅을 통해 시간 차이를 구하는 법을 배웠습니다.
<br>

Min: 5월 1주차 문제 풀이

---

05월/1주차/[BOJ] 4와 7/Mun.java
05월/1주차/[BOJ] The Game of Death/Mun.java
05월/1주차/[BOJ] 과제는 끝나지 않아!/Mun.java
05월/1주차/[PRGRMS] [3차] 방금그곡/Mun.java

- [4와 7](https://www.acmicpc.net/problem/2877)
- [과제는 끝나지 않아!](https://www.acmicpc.net/problem/17952)
- [The Game of Death](https://www.acmicpc.net/problem/11558)
- [[3차] 방금그곡](https://school.programmers.co.kr/learn/courses/30/lessons/17683)
<br>
🙅‍♀️
<br>
이진법에 대해 다시 한번 생각해 보는 기회가 된 것 같습니다.
<br>
이진법 활용법에 대해 좀 더 공부하면 좋을 것 같습니다.
<br>

Mun: 5월 1주차 문제 풀이

---

05월/1주차/[BOJ] 4와 7/Mun.java
05월/1주차/[BOJ] The Game of Death/Min.java
05월/1주차/[BOJ] The Game of Death/Mun.java
05월/1주차/[BOJ] 과제는 끝나지 않아!/Min.java
05월/1주차/[BOJ] 과제는 끝나지 않아!/Mun.java
05월/1주차/[PRGRMS] [3차] 방금그곡/Min.java
05월/1주차/[PRGRMS] [3차] 방금그곡/Mun.java

- [4와 7](https://www.acmicpc.net/problem/2877)
- [과제는 끝나지 않아!](https://www.acmicpc.net/problem/17952)
- [The Game of Death](https://www.acmicpc.net/problem/11558)
- [[3차] 방금그곡](https://school.programmers.co.kr/learn/courses/30/lessons/17683)

[SOLVE] 민문리 5월 1주차 문제 풀이

---

05월/2주차/[BOJ] 여러분의 다리가 되어 드리겠습니다!/Mun.java
05월/2주차/[BOJ] 큐 2/Mun.java
05월/2주차/[BOJ] 프린터 큐/Mun.java
05월/2주차/[PRGRMS] 무인도 여행/Mun.java

- [여러분의 다리가 되어 드리겠습니다!](https://www.acmicpc.net/problem/17352)
- [큐2](https://www.acmicpc.net/problem/18258)
- [프린터 큐](https://www.acmicpc.net/problem/1966)
- [무인도 여행](https://school.programmers.co.kr/learn/courses/30/lessons/154540)
<br>
🙅‍♀️
<br>
- Deque 활용법에 대해 알게 되었습니다.
- char -> int 과정에서 숫자를 제대로 출력하기 위한 방법을 알게 되었습니다.
<br>

Mun: 5월 2주차 문제 풀이

---

05월/2주차/[BOJ] 여러분의 다리가 되어 드리겠습니다!/Min.java
05월/2주차/[BOJ] 여러분의 다리가 되어 드리겠습니다!/Mun.java
05월/2주차/[BOJ] 큐 2/Min.java
05월/2주차/[BOJ] 큐 2/Mun.java
05월/2주차/[BOJ] 프린터 큐/Min.java
05월/2주차/[BOJ] 프린터 큐/Mun.java
05월/2주차/[PRGRMS] 무인도 여행/Min.java
05월/2주차/[PRGRMS] 무인도 여행/Mun.java

- [여러분의 다리가 되어 드리겠습니다!](https://www.acmicpc.net/problem/17352)
- [큐2](https://www.acmicpc.net/problem/18258)
- [프린터 큐](https://www.acmicpc.net/problem/1966)
- [무인도 여행](https://school.programmers.co.kr/learn/courses/30/lessons/154540)
<br>

[SOLVE] 민문리 5월 2주차 문제 풀이

---

05월/3주차/[BOJ] 직사각형 네개의 합집합의 면적 구하기/Mun.java
05월/3주차/[BOJ] 파일 정리/Mun.java

- [직사각형 네개의 합집합의 면적 구하기](https://www.acmicpc.net/problem/2669)
- [파일 정리](https://www.acmicpc.net/problem/20291)
<br>
- [RBY팡!](https://www.acmicpc.net/problem/5577)
구슬을 문자열로 연결했습니다. 바꾸는 과정에 StringBuilder를 사용해 예제는 해결했지만, 메모리 초과가 발생했습니다.
문자열 말고 다른 방법으로 시도해 볼 계획입니다.
<br>
- [리코쳇 로봇](https://school.programmers.co.kr/learn/courses/30/lessons/169199)
처음에 BFS 풀이를 떠올렸다가 오랜만에 DFS를 사용해볼까 싶어서 시도했는데, 시간 내에 해결하지 못했습니다.
그냥 처음 생각했던 BFS 풀이 방법으로 다시 풀 계획입니다!!!
<br>
- Split에서 .을 기준으로 자를 때 주의할 점을 알았습니다.
- RGB팡 문제에서 StringBuilder를 사용하면서 느낀점으로 
<br>
메모리 초과 문제가 자주 발생하는 것을 느꼈기 때문에 공간복잡도에 대해 다시 공부하며 이를 보완해야 겠다고 느꼈습니다.

Mun: 5월 3주차 문제 풀이

---

05월/3주차/[BOJ] 직사각형 네개의 합집합의 면적 구하기/Min.java
05월/3주차/[BOJ] 파일 정리/Min.java
05월/3주차/[PRGRMS] 리코쳇 로봇/Min.java

- [직사각형 네개의 합집합의 면적 구하기](https://www.acmicpc.net/problem/2669)
- [파일 정리](https://www.acmicpc.net/problem/20291)
- [리코쳇 로봇](https://school.programmers.co.kr/learn/courses/30/lessons/169199)
<br>
- [RBY팡!](https://www.acmicpc.net/problem/5577)
공의 색깔을 변화 시켜 같은 색을 지우고 공들을 합쳤을 때의 풀이 과정이 아직 떠오르지 않습니다.
- 다른 풀이를 참고해볼 예정입니다.
<br>
- split() 메서드를 사용할 때 "." 을 기준으로 split 할 때는 split("\\.") 으로 작성해야한다는 점을 다시 복습하게 되었습니다.
<br>

Min: 5월 3주차 문제 풀이

---

05월/3주차/[BOJ] 직사각형 네개의 합집합의 면적 구하기/Min.java
05월/3주차/[BOJ] 직사각형 네개의 합집합의 면적 구하기/Mun.java
05월/3주차/[BOJ] 파일 정리/Min.java
05월/3주차/[BOJ] 파일 정리/Mun.java
05월/3주차/[PRGRMS] 리코쳇 로봇/Min.java

- [직사각형 네개의 합집합의 면적 구하기](https://www.acmicpc.net/problem/2669)
- [파일 정리](https://www.acmicpc.net/problem/20291)
- [RBY팡!](https://www.acmicpc.net/problem/5577)
- [리코쳇 로봇](https://school.programmers.co.kr/learn/courses/30/lessons/169199)
<br>
- [RBY팡!](https://www.acmicpc.net/problem/5577)
<br>

[SOLVE] 민문리 5월 3주차 문제 풀이

---

05월/3주차/[PRGRMS] 리코쳇 로봇/Mun.java
05월/4주차/[BOJ] 놀이공원/Mun.java
05월/4주차/[BOJ] 피터팬 프레임/Mun.java

- [놀이공원](https://www.acmicpc.net/problem/2594)
- [피터팬 프레임](https://www.acmicpc.net/problem/3054)
- [리코쳇 로봇](https://school.programmers.co.kr/learn/courses/30/lessons/169199) (5월 3주차 문제)
<br>
- [연구소](https://www.acmicpc.net/problem/14502)
- [줄 서는 방법](https://school.programmers.co.kr/learn/courses/30/lessons/12936)
<br>
<br>

Mun: 5월 4주차 문제 풀이

---

06월/1주차/[BOJ] 양 한마리 양 두마리/Min.java
06월/1주차/[BOJ] 탈출/Min.java
06월/1주차/[BOJ] 후보 추천하기/Min.java

- [양 한마리 양 두마리](https://www.acmicpc.net/problem/11123)
- [탈출](https://www.acmicpc.net/problem/3055)
- [후보 추천하기](https://www.acmicpc.net/problem/1713)
- []()
<br>
- [줄 서는 방법](https://school.programmers.co.kr/learn/courses/30/lessons/12936)
- 풀이를 봤는데 특정 부분이 이해가 가지 않아 풀이를 봐도 끝까지 이해하지 못했습니다....🫠
- 스터디를 통해 이해가지 않은 부분을 짚고 넘어갈 볼 예정입니다
<br>
<br>

Min: 6월 1주차 문제 풀이

---

06월/1주차/[BOJ] 양 한마리 양 두마리/Min.java
06월/1주차/[BOJ] 양 한마리 양 두마리/Mun.java
06월/1주차/[BOJ] 탈출/Min.java
06월/1주차/[BOJ] 탈출/Mun.java
06월/1주차/[BOJ] 후보 추천하기/Min.java
06월/1주차/[BOJ] 후보 추천하기/Mun.java
06월/1주차/[PRGRMS] 줄 서는 방법/Mun.java

- [양 한마리... 양 두마리...](https://www.acmicpc.net/problem/11123)
- [후보 추천하기](https://www.acmicpc.net/problem/1713)
- [탈출](https://www.acmicpc.net/problem/3055)
- [줄 서는 방법
](https://school.programmers.co.kr/learn/courses/30/lessons/12936)
<br>

[SOLVE] 민문리 6월 1주차 문제 풀이

---

06월/2주차/[BOJ] 특정 거리의 도시 찾기/Mun.java
06월/2주차/[BOJ] 효율적인 해킹/Mun.java

- [특정 거리의 도시 찾기](https://www.acmicpc.net/problem/18352)
- []()
<br>
- [최단 경로](https://www.acmicpc.net/problem/1753)
- [효율적인 해킹](https://www.acmicpc.net/problem/1325)
- [행렬 테두리 회전하기](https://school.programmers.co.kr/learn/courses/30/lessons/77485)
<br>
<br>
다음부터는 문제 풀이를 빨리 시작하겠습니다. 또 메모리를 적게 사용하는 방법을 생각하겠습니다.

Mun: 6월 2주차 문제 풀이

---

06월/2주차/[BOJ] 최단경로/Min.java
06월/2주차/[BOJ] 특정 거리의 도시 찾기/Min.java
06월/2주차/[BOJ] 효율적인 해킹/Min.java

- [최단 경로](https://www.acmicpc.net/problem/1753)
- [특정 거리의 도시 찾기](https://www.acmicpc.net/problem/18352)
- [효율적인 해킹](https://www.acmicpc.net/problem/1325)
<br>
- [행렬 테두리 회전하기](https://school.programmers.co.kr/learn/courses/30/lessons/77485)
- 처음에 문제를 잘못 이해했는데 제대로 이해를 뒤늦게 하는 바람에 문제를 제대로 생각할 수 있는 시간이 부족했습니다..
- 다시 시간을 충분히 갖고 풀어볼 생각입니다.
<br>
<br>

Min: 6월 2주차 문제 풀이

---

05월/4주차/[BOJ] 연구소/Min.java
06월/3주차/[BOJ] NBA 농구/Min.java
06월/3주차/[BOJ] 카드 놓기/Min.java
06월/3주차/[PRGRMS] 행렬 테두리 회전하기/Min.java

- [연구소](https://www.acmicpc.net/problem/14502) (5월 4주차 문제)
- [NBA 농구](https://www.acmicpc.net/problem/2852)
- [카드 놓기](https://www.acmicpc.net/problem/5568)
- [행렬 테두리 회전하기](https://school.programmers.co.kr/learn/courses/30/lessons/77485)
<br>
- [Maaaaaaaaaze](https://www.acmicpc.net/problem/16985)
- 아직 3차원 배열이 능숙하지 못해 활용하는데 어려움이 있었습니다.
3차원 배열을 이용한 문제를 더 풀어볼 예정입니다.
<br>
- String.format() 메서드 활용법을 다시 공부하게 되었습니다.
- 백트래킹 풀이법에 대해 조금 더 감을 잡은 것 같습니다.
<br>

Min: 6월 3주차 문제풀이

---

06월/4주차/[BOJ] 도영이가 만든 맛있는 음식/Min.java
06월/4주차/[BOJ] 암호 만들기/Min.java
06월/4주차/[BOJ] 차이를 최대로/Min.java

- [도영이가 만든 맛있는 음식](https://www.acmicpc.net/problem/2961)
- [암호 만들기](https://www.acmicpc.net/problem/1759)
- [차이를 최대로](https://www.acmicpc.net/problem/10819)
<br>
- [디펜스 게임](https://school.programmers.co.kr/learn/courses/30/lessons/142085#qna)
- 처음에는 테스트케이스 다 맞춰서 풀었는데 막상 채점해보니 틀려서 풀이를 봤었는데 나와있는 풀이가 이해가지 않았습니다...
- ### 개선 계획
- 다른 풀이를 찾아보거나 해설을 더 봐야할거같습니다.
<br>
- `.compareTo()` : 비교된 문자열이 사전순으로 더 클 경우 양수 반환, 작을 경우 음수 반환, 같을 경우 0반환.  오랜만에 사용했는데 헷갈려서 여기에 적어둡니다..!
<br>

Min: 6월 4주차 문제 풀이

---

06월/4주차/[BOJ] 도영이가 만든 맛있는 음식/Min.java
06월/4주차/[BOJ] 도영이가 만든 맛있는 음식/Mun.java
06월/4주차/[BOJ] 암호 만들기/Min.java
06월/4주차/[BOJ] 암호 만들기/Mun.java
06월/4주차/[BOJ] 차이를 최대로/Min.java
06월/4주차/[BOJ] 차이를 최대로/Mun.java

- [암호 만들기](https://www.acmicpc.net/problem/1759)
- [차이를 최대로](https://www.acmicpc.net/problem/10819)
- [도영이가 만든 맛있는 음식](https://www.acmicpc.net/problem/2961)
- [디펜스 게임](https://school.programmers.co.kr/learn/courses/30/lessons/142085)
- [디펜스 게임](https://school.programmers.co.kr/learn/courses/30/lessons/142085)

[SOLVE] 민문리 6월 4주차 문제 풀이

---

06월/5주차/[BOJ] PPAP/Min.java
06월/5주차/[BOJ] 가희와 키워드/Min.java
06월/5주차/[BOJ] 문자열 집합/Min.java
06월/5주차/[PRGRMS] 괄호 변환/Min.java

- [PPAP](https://www.acmicpc.net/problem/16120)
- [가희와 키워드](https://www.acmicpc.net/problem/22233)
- [문자열 집합](https://www.acmicpc.net/problem/14425)
- [괄호 변환](https://school.programmers.co.kr/learn/courses/30/lessons/60058)
<br>
<br>
- 시간 복잡도에 대해 더 생각해보게 되었습니다.
<br>

Min: 6월 5주차 문제풀이

---

07월/1주차/[BOJ] 사탕/Mun.java
07월/1주차/[BOJ] 안테나/Mun.java
07월/1주차/[BOJ] 카드 정렬하기/Mun.java
07월/1주차/[PRGRMS] 수식 최대화/Mun.java

- [카드 정렬하기](https://www.acmicpc.net/problem/1715)
- [안테나](https://www.acmicpc.net/problem/18310)
- [사탕](https://www.acmicpc.net/problem/11256)
- [수식 최대화](https://school.programmers.co.kr/learn/courses/30/lessons/67257)
<br>
🙅‍♀️
<br>
ArrayList를 복사하는 방법에 대해 복습할 수 있었습니다.
또 정규식에 대해서도 복습할 수 있었습니다.
참고한 링크
- [[공부한 것] String.matches는 왜 성능에 안 좋을까?](https://velog.io/@dlguswl936/%EA%B3%B5%EB%B6%80%ED%95%9C-%EA%B2%83-String.matches%EB%8A%94-%EC%99%9C-%EC%84%B1%EB%8A%A5%EC%97%90-%EC%95%88-%EC%A2%8B%EC%9D%84%EA%B9%8C)
<br>
정규식을 검색 없이 사용할 수 있도록 보완해야 될 것 같습니다.

Mun: 7월 1주차 문제 풀이

---

03월/1주차/[BOJ] 상자넣기/Min.java
07월/1주차/[BOJ] 사탕/Min.java
07월/1주차/[BOJ] 사탕/Mun.java
07월/1주차/[BOJ] 안테나/Min.java
07월/1주차/[BOJ] 안테나/Mun.java
07월/1주차/[BOJ] 카드 정렬하기/Min.java
07월/1주차/[BOJ] 카드 정렬하기/Mun.java
07월/1주차/[PRGRMS] 수식 최대화/Mun.java

- [카드 정렬하기](https://www.acmicpc.net/problem/1715)
- [안테나](https://www.acmicpc.net/problem/18310)
- [사탕](https://www.acmicpc.net/problem/11256)
- [수식 최대화](https://school.programmers.co.kr/learn/courses/30/lessons/67257)
Min
- [상자 넣기](https://www.acmicpc.net/problem/1965) (3월 1주차 문제)

[SOLVE] 민문리 7월 1주차 문제 풀이

---

07월/2주차/[BOJ] 로마 숫자 만들기/Mun.java
07월/2주차/[BOJ] 진우의 민트초코우유/Mun.java
07월/2주차/[PRGRMS] 테이블 해시 함수/Mun.java

- [로마 숫자 만들기](https://www.acmicpc.net/problem/16922)
- [진우의 민트초코우유](https://www.acmicpc.net/problem/20208)
- [테이블 해시 함수](https://school.programmers.co.kr/learn/courses/30/lessons/147354)
<br>
- [안녕](https://www.acmicpc.net/problem/1535)
점화식을 생각해내지 못했습니다.
풀이를 듣고 이해 후 다시 도전하겠습니다!
<br>
- 자바에서의 XOR 연산 방법에 대해 알게되었습니다.
참고 링크: [자바에서 XOR 연산을 활용한 알고리즘 문제 해결](https://f-lab.kr/insight/xor-operation-in-java-20240714?gad_source=2&gclid=Cj0KCQiAy8K8BhCZARIsAKJ8sfS-coDsr2zm2I63njpzRVyzgugfez-f2HBHuwsrQEInIImrUJ8ONSgaAhGdEALw_wcB)
- 맨해튼 거리 공식에 대해 복습할 수 있었습니다. 
앞으로 거리를 구하는 문제에서 잘 사용해야 겠다고 느꼈습니다.
참고 링크: [맨하탄 거리(Manhattan Distance) 개념과 구현해보기](https://needjarvis.tistory.com/455)
<br>

Mun: 7월 2주차 문제 풀이

---

07월/2주차/[BOJ] 로마 숫자 만들기/Min.java
07월/2주차/[BOJ] 로마 숫자 만들기/Mun.java
07월/2주차/[BOJ] 안녕/Min.java
07월/2주차/[BOJ] 진우의 민트초코우유/Mun.java
07월/2주차/[PRGRMS] 테이블 해시 함수/Min.java
07월/2주차/[PRGRMS] 테이블 해시 함수/Mun.java

- [로마 숫자 만들기](https://www.acmicpc.net/problem/16922)
- [안녕](https://www.acmicpc.net/problem/1535)
- [진우의 민트초코우유](https://www.acmicpc.net/problem/20208)
- [테이블 해시 함수](https://school.programmers.co.kr/learn/courses/30/lessons/147354)

[SOLVE] 민문리 7월 2주차 문제 풀이

---

07월/3주차/[BOJ] 성적 통계/Min.java
07월/3주차/[BOJ] 자리배정/Min.java
07월/3주차/[PRGRMS] 가장 큰 정사각형 찾기/Min.java

- [성적 통계](https://www.acmicpc.net/problem/5800)
- [자리배정](https://www.acmicpc.net/problem/10157)
- [가장 큰 정사각형 찾기](https://school.programmers.co.kr/learn/courses/30/lessons/12905)
<br>
- 구현 방법을 떠올리지 못했습니다.
- 시간을 갖고 생각해보겠습니다.
<br>
<br>
- 난이도 있는 구현을 좀 더 연습해볼 필요가 있는 것 같습니다.

Min: 7월 3주차 문제 풀이

---

07월/3주차/[BOJ] 성적 통계/Mun.java
07월/3주차/[BOJ] 자리배정/Mun.java
07월/3주차/[PRGRMS] 가장 큰 정사각형 찾기/Mun.java

- [성적 통계](https://www.acmicpc.net/problem/5800)
- [자리배정](https://www.acmicpc.net/problem/10157)
- [안녕 (7월 2주차 문제)](https://www.acmicpc.net/problem/1535)
- [가장 큰 정사각형 찾기](https://school.programmers.co.kr/learn/courses/30/lessons/12905)
<br>
- [사다리 조작](https://www.acmicpc.net/problem/15684)
풀이 방법을 잘 떠올리지 못했습니다.
풀이를 보고 이해해보며 다시 풀어보겠습니다!
<br>
이번 주차 프로그래머스 문제(가장 큰 정사각형 찾기) 같은 내용은 점화식을 세워서 풀 수 있다는 점을 기억했습니다.
<br>
시간이 오래 걸릴 것 같다고 느낄 때 DP로 접근하는 방법을 생각해낼 수 있도록 노력해야 할 것 같습니다!
<br>

Mun: 7월 3주차 문제 풀이

---

07월/4주차/[BOJ] 친구비/Mun.java
07월/4주차/[BOJ] 폴짝폴짝/Mun.java
07월/4주차/[BOJ] 현수막/Mun.java
07월/4주차/[PRGRMS] 거리두기 확인하기/Mun.java

- [친구비](https://www.acmicpc.net/problem/16562)
- [폴짝폴짝](https://www.acmicpc.net/problem/1326)
- [현수막](https://www.acmicpc.net/problem/14716)
- [거리두기 확인하기](https://school.programmers.co.kr/learn/courses/30/lessons/81302)
<br>
🙅‍♀️
<br>
<br>

Mun: 7월 4주차 문제 풀이

---

07월/4주차/[BOJ] 친구비/Friend.java
07월/4주차/[BOJ] 친구비/Mun.java
07월/4주차/[BOJ] 폴짝폴짝/Mun.java
07월/4주차/[BOJ] 현수막/Min.java
07월/4주차/[BOJ] 현수막/Mun.java
07월/4주차/[PRGRMS] 거리두기 확인하기/Min.java
07월/4주차/[PRGRMS] 거리두기 확인하기/Mun.java

- [친구비](https://www.acmicpc.net/problem/16562)
- [폴짝폴짝](https://www.acmicpc.net/problem/1326)
- [현수막](https://www.acmicpc.net/problem/14716)
- [거리두기 확인하기](https://school.programmers.co.kr/learn/courses/30/lessons/81302)
<br>

[SOLVE] 민문리 7월 4주차 문제 풀이

---

08월/1주차/[BOJ] 단어 뒤집기 2/Min.java
08월/1주차/[BOJ] 좋다/Min.java
08월/1주차/[BOJ] 콰트로치즈피자/Min.java

- [단어 뒤집기 2](https://www.acmicpc.net/problem/17413)
- [좋다](https://www.acmicpc.net/problem/1253)
- [콰트로치즈피자](https://www.acmicpc.net/problem/27964) 
<br>
- [하노이의 탑](https://school.programmers.co.kr/learn/courses/30/lessons/12946)
알고리즘 이해 부족
해당 알고리즘의 기초적인 문제를 더 풀어봐야 될 것 같습니다.
<br>
- 투포인터 알고리즘에 대해 공부해볼 수 있었습니다.
<br>

Min: 8월 1주차 문제 풀이

---

08월/1주차/[BOJ] 단어 뒤집기 2/Min.java
08월/1주차/[BOJ] 단어 뒤집기 2/Mun.java
08월/1주차/[BOJ] 좋다/Min.java
08월/1주차/[BOJ] 좋다/Mun.java
08월/1주차/[BOJ] 콰트로치즈피자/Min.java
08월/1주차/[BOJ] 콰트로치즈피자/Mun.java

- [좋다](https://www.acmicpc.net/problem/1253)
- [단어 뒤집기 2](https://www.acmicpc.net/problem/17413)
- [콰트로치즈피자](https://www.acmicpc.net/problem/27964)
- [하노이의 탑](https://school.programmers.co.kr/learn/courses/30/lessons/12946)
- [하노이의 탑](https://school.programmers.co.kr/learn/courses/30/lessons/12946)

[SOLVE] 민문리 8월 1주차 문제 풀이

---

08월/2주차/[BOJ] 신입 사원/Min.java
08월/2주차/[BOJ] 카드 합체 놀이/Min.java
08월/2주차/[PRGRMS] 우박수열 정적분/Min.java

- [신입사원](https://www.acmicpc.net/problem/1946)
- [카드 합체 놀이](https://www.acmicpc.net/problem/15903)
- [우박수열 정적분](https://school.programmers.co.kr/learn/courses/30/lessons/134239)
<br>
- [센서](https://school.programmers.co.kr/learn/courses/30/lessons/134239)
문제 접근 방식을 찾지 못했습니다.
풀이를 참고해보겠습니다.
<br>
<br>

Min: 8월 2주차 문제풀이

---

08월/2주차/[BOJ] 센서/Mun.java
08월/2주차/[BOJ] 신입 사원/Min.java
08월/2주차/[BOJ] 신입 사원/Mun.java
08월/2주차/[BOJ] 카드 합체 놀이/Min.java
08월/2주차/[BOJ] 카드 합체 놀이/Mun.java
08월/2주차/[PRGRMS] 우박수열 정적분/Min.java

- [센서](https://www.acmicpc.net/problem/2212)
- [신입 사원](https://www.acmicpc.net/problem/1946)
- [카드 합체 놀이](https://www.acmicpc.net/problem/15903)
- [우박수열 정적분](https://school.programmers.co.kr/learn/courses/30/lessons/134239)

[SOLVE] 민문리 8월 2주차 문제 풀이

---

08월/3주차/[BOJ] 경비원/Min.java
08월/3주차/[BOJ] 숫자 정사각형/Min.java
08월/3주차/[PRGRMS] 광물 캐기/Min.java

- [경비원](https://www.acmicpc.net/problem/2564)
- [숫자 정사각형](https://www.acmicpc.net/problem/1051)
- [광물 캐기](https://school.programmers.co.kr/learn/courses/30/lessons/172927)
<br>
- [뱀](https://www.acmicpc.net/problem/3190)
구현 방법을 아직 생각해내지 못했습니다.
풀이를 통해 공부해볼 예정입니다.
<br>
<br>

Min: 8월 3주차 문제 풀이

---

08월/4주차/[BOJ] 기상캐스터/Mun.java
08월/4주차/[BOJ] 임시 반장 정하기/Mun.java
08월/4주차/[PRGRMS] 문자열 압축/Mun.java

- [기상캐스터](https://www.acmicpc.net/problem/10709)
- [임시 반장 정하기](https://www.acmicpc.net/problem/1268)
- [문자열 압축](https://school.programmers.co.kr/learn/courses/30/lessons/60057)
<br>
- [⚾](https://www.acmicpc.net/problem/17281)
<br>
<br>

Mun: 8월 4주차 문제 풀이

---

09월/2주차/[BOJ] Java vs C++/Min.java
09월/2주차/[BOJ] 치킨 배달/Min.java
09월/2주차/[BOJ] 카드1/Min.java
09월/2주차/[PRGRMS] 퍼즐 게임 챌린지/Min.java

- [Java vs C++](https://www.acmicpc.net/problem/3613)
- [치킨 배달](https://www.acmicpc.net/problem/15686)
- [카드1](https://www.acmicpc.net/problem/2161)
- [퍼즐 게임 챌린지](https://school.programmers.co.kr/learn/courses/30/lessons/340212)
<br>
<br>
- 이분 탐색에 대해 다시 공부해볼 수 있었습니다.
<br>
- 문제를 보고 효율적인 알고리즘 접근 방식이 무엇인지 생각해내는 감각을 키워야 될 것 같습니다.

Min: 9월 2주차 문제 풀이

---

09월/2주차/[BOJ] Java vs C++/Min.java
09월/2주차/[BOJ] Java vs C++/Mun.java
09월/2주차/[BOJ] 치킨 배달/Min.java
09월/2주차/[BOJ] 치킨 배달/Mun.java
09월/2주차/[BOJ] 카드1/Min.java
09월/2주차/[BOJ] 카드1/Mun.java
09월/2주차/[PRGRMS] 퍼즐 게임 챌린지/Min.java

- [카드1](https://www.acmicpc.net/problem/2161)
- [치킨 배달](https://www.acmicpc.net/problem/15686)
- [Java vs C++](https://www.acmicpc.net/problem/3613)
- [퍼즐 게임 챌린지](https://school.programmers.co.kr/learn/courses/30/lessons/340212)

[SOLVE] 민문리 9월 2주차 문제 풀이

---

09월/4주차/[BOJ] 나는 위대한 슈퍼스타K/Min.java
09월/4주차/[BOJ] 삼각형 만들기/Min.java
09월/4주차/[BOJ] 전구와 스위치/Min.java

- [나는 위대한 슈퍼스타K](https://www.acmicpc.net/problem/2865)
- [삼각형 만들기](https://www.acmicpc.net/problem/1448)
- [전구와 스위치](https://www.acmicpc.net/problem/2138)
<br>
- [후보키 만들기](https://school.programmers.co.kr/learn/courses/30/lessons/42890)
- 최소성을 만족시키는 조건을 생각해내는 과정에서 어려움이 있었습니다.
- 풀이를 보고 다시 풀어보겠습니다.
<br>
<br>
- 난이도가 조금 있는 그리디 문제를 자주 접해서 연습해봐야겠다는 생각이 들었습니다.

Min: 9월 4주차 문제 풀이
